### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by Ciellix** [Drathonix/experiencedworlds2#2]
experiencedworlds-2.0.3+1.21+neoforge

Trying too create a Singleplayer world, only happened after I installed this mod, also crashes my server whenever you try and load in the world, but does not crash the client

https://mclo.gs/wZnYrUt Singleplayer crash log

https://mclo.gs/8BBe3pS Server crash log

Also sorry if Iv formatted this incorrectly, I think I followed the prompt okayish

**Comment by Drathonix** [comment]
Cause is missing mixin refmap. Architectury is failing to put the refmap in the jar for some reason.

Seems like this is a problem with Neoforge only. I'll put out a patch ASAP.

**Comment by Ciellix** [comment]
ah, okay thanks

**Comment by Drathonix** [comment]
Actually I'm wrong. Refmaps are unnecessary in NeoForge. This is a problem with not being commented out using stonecutter versioning. 
```java
@Shadow
    private static @NotNull CompletableFuture<Void> tryWriteAsync(Path par1, CompoundTag par2) {
        return null;
    }
```

Good news is that I've fixed the problem, download the V 2.0.4 file from modrinth.

**Comment by Ciellix** [comment]
okay ill test

**Comment by Ciellix** [comment]
ye it fixed it, thanks
